### PR TITLE
Added first few contextual links

### PR DESCRIPTION
**Pull request by eldang**
Partial progress on #4
Caveats:

* City Council Districts just link to a general info page, because I couldn’t find a useful way to go direct to the district without losing representatives’ info
* Elementary Schools are a bit special case heavy.  There must be a better way to handle that.

### CODE REVIEW

**Comment by eldang** [comment]
I should add: if you want to wait until more of these are done before merging, I expect to be able to do a few more on Tuesday.  At least the other schools and Congressional districts.

**Comment by sethvincent** [comment]
This is great. Yes, let's keep it open for now.

**Comment by eldang** [comment]
:+1: I'll leave another comment when I either think I've done all I can or see myself running out of time for a while.

**Comment by eldang** [comment]
Oh, and while I'm thinking about this, is there a simple way to generate the URLs or URL stubs for (e.g.) schools in the data retrieval stage instead of in `location-narrative.js` ?  I think the way I did this currently is fine for legislative districts, where it's just stripping text out to get the district number, but I don't like all the special case find and replaces I glommed into line 76.  (If you can just point me to the right file I can probably figure the rest out, or is the data object being returned by something outside the scope of this project?)

**Comment by sethvincent** [comment]
@eldang all the data is coming from here: https://github.com/openseattle/seattle-boundaries

So it may be the best place to add metadata in some cases.

**Comment by eldang** [comment]
Confession: I'm about to go on vacation and haven't had time to address this.  I'm happy to pick it back up in early February, but just felt I should warn you in case you want to merge the partial work meanwhile.

**Comment by eldang** [comment]
Closing this as old and presumably out of date.

**Pull request closed without merging**
